language: generic # don't install any environment
script:
  - bash ./deploy.sh
env:
  global:
  - APL_LOC_DEPLOY_ID: "8ee404f4-9d01-4d82-8dc7-dcf8a99e2fc0"
  - APL_LOC_ARTIFACT_ID: "dd8d371b-e713-4388-897e-58df81f01a95"
  - APL_STACK_ID: "96956ab8-c9a8-4438-b549-54b5c54d8936"
  - APL_RElEASE_ID: "ea8b68e8-81f7-4ed2-bd70-0c535df69832"
  - APL_STACK_COMPONENT_ID: "347409b8-d00e-4e85-9dc2-8cf56138b821"
  - APL_COMPONENT_SERVICE_ID: "ct-deployment"
  - APL_ARTIFACT_NAME: "acme-air"
  - APL_CMD_RELEASE: "v0.1.18"